(function(){ "use strict";
const KEY="bs10_marine_runtime_v1";
const state=JSON.parse(localStorage.getItem(KEY)||'{"vessel":{},"maintenance":[],"documents":[],"expenses":[],"catches":[],"checklists":[],"observations":[],"messages":[],"academyProgress":{},"digitalTwin":{"engineHours":0,"fuelPct":100,"status":"READY"}}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const uid=p=>p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toFixed(2):"—";
const add=(type,data)=>{(state[type]||(state[type]=[])).unshift({id:uid(type),createdAt:new Date().toISOString(),...data});save();sync(type,state[type][0]);return state[type][0]};
async function sync(type,item){try{if(window.SupabaseSync?.ready){const safe={id:item?.id||uid(type),...item};await SupabaseSync.pushCollection(type,[safe])}}catch(e){console.warn("Marine sync",e)}}catch(e){console.warn("Marine sync",e)}}
async function bmkg(path){if(window.MarineExternal?.bmkg?.json)return MarineExternal.bmkg.json(path);const r=await fetch("https://maritim.bmkg.go.id/marine2026-data/"+path,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error("BMKG HTTP "+r.status);return r.json()}});if(!r.ok)throw new Error("BMKG HTTP "+r.status);return r.json()}
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function list(c,id,arr,fn){const e=c.querySelector("#"+id);if(e)e.innerHTML=(arr||[]).slice(0,30).map(x=>'<div class="mw-item">'+fn(x)+'</div>').join("")||'<span class="mw-muted">Belum ada data.</span>'}
const WB={el:null,current:"overview",tabs:[["navigation","🧭 Navigasi"],["weather","🌦️ Cuaca"],["fishing","🎣 Fishing"],["safety","🛟 Safety"],["vessel","🚢 Kapal"],["maintenance","🔧 Maintenance"],["documents","📄 Dokumen"],["economy","💰 Ekonomi"],["social","👥 Social"],["messenger","💬 Messenger"],["data","📊 Data"],["academy","🎓 Academy"],["camera","📷 Camera"],["checklist","✅ Checklist"],["digital-twin","🧩 Digital Twin"],["ais","📡 AIS"],["radar","📻 Radar"],["ai","🤖 Copilot"]],
ensure(){if(this.el)return;this.el=document.createElement("div");this.el.className="marine-workbench";this.el.innerHTML='<div class="marine-workbench-inner"><div class="mw-head"><div><span class="eyebrow">MARINE OS • FULL RUNTIME</span><h2 id="mwTitle">Marine Workbench</h2></div><button class="btn mw-close">✕</button></div><div class="mw-tabs" id="mwTabs"></div><div id="mwContent"></div></div>';document.body.appendChild(this.el);this.el.querySelector(".mw-close").onclick=()=>this.close()},
open(k){this.ensure();this.current=k||"navigation";this.el.classList.add("open");this.render()},close(){this.el?.classList.remove("open")},
render(){const tabs=this.el.querySelector("#mwTabs");tabs.innerHTML=this.tabs.map(x=>'<button class="btn sm '+(x[0]===this.current?"primary-inline":"")+'" data-mw="'+x[0]+'">'+x[1]+"</button>").join("");tabs.onclick=e=>{const b=e.target.closest("[data-mw]");if(b){this.current=b.dataset.mw;this.render()}};this.el.querySelector("#mwTitle").textContent=this.tabs.find(x=>x[0]===this.current)?.[1]||"Marine Workbench";const c=this.el.querySelector("#mwContent");c.innerHTML=view(this.current);bind(c,this.current)},
};
function view(k){
if(k==="navigation")return '<div class="mw-grid"><div class="mw-card"><h4>Rute & ETA</h4><div class="mw-row"><input id="mwLat" type="number" step="any" placeholder="Latitude tujuan"><input id="mwLon" type="number" step="any" placeholder="Longitude tujuan"></div><div class="mw-row"><input id="mwSog" type="number" step=".1" placeholder="SOG knot"><button class="btn primary-inline" id="mwRoute">Hitung</button></div><div id="mwRouteOut" class="mw-status">Masukkan tujuan.</div></div><div class="mw-card"><h4>Voyage Recorder</h4><div class="mw-value" id="mwTrackCount">0</div><p class="mw-muted">titik track lokal.</p><button class="btn" id="mwExportTrack">Ekspor JSON</button></div></div>';
if(k==="weather")return '<div class="mw-grid"><div class="mw-card"><h4>BMKG Maritime</h4><div id="mwWeather">Mencari posisi GNSS…</div><button class="btn" id="mwWeatherRefresh">Refresh BMKG</button><div class="mw-source">Sumber resmi BMKG Data Maritim.</div></div><div class="mw-card"><h4>Warnings</h4><div id="mwWarnings">Kanal warning BMKG tersedia melalui katalog resmi.</div></div></div>';
if(k==="fishing")return '<div class="mw-grid"><div class="mw-card"><h4>Fishing Intelligence</h4><div class="mw-value" id="fishScore">—</div><p class="mw-muted">Skor indikatif, bukan jaminan ikan.</p><button class="btn primary-inline" id="fishCalc">Analisis lokasi sekarang</button></div><div class="mw-card"><h4>Observasi tangkapan</h4><div class="mw-row"><input id="fishSpecies" placeholder="Jenis ikan"><input id="fishKg" type="number" placeholder="kg"><button class="btn" id="fishSave">Simpan</button></div><div id="fishList" class="mw-list"></div></div></div>';
if(k==="safety")return '<div class="mw-grid"><div class="mw-card mw-warn"><h4>Safety Guardian</h4><div id="safeStatus">Menilai GNSS, jaringan dan anchor watch…</div><button class="btn danger" id="mwSos">Emergency checklist</button></div><div class="mw-card"><h4>Anchor Watch</h4><div class="mw-row"><input id="anchorRadius" type="number" value="100" placeholder="meter"><button class="btn" id="anchorSet">Set posisi</button></div><div id="anchorStatus">Belum aktif.</div></div></div>';
if(k==="vessel")return '<div class="mw-grid"><div class="mw-card"><h4>Profil Kapal</h4><div class="mw-row"><input id="vName" placeholder="Nama kapal"><input id="vCaptain" placeholder="Nahkoda"></div><div class="mw-row"><input id="vGross" type="number" placeholder="GT"><input id="vCargo" placeholder="Muatan"></div><button class="btn primary-inline" id="vSave">Simpan</button></div><div class="mw-card"><h4>Data tersimpan</h4><pre id="vJson" class="mw-muted"></pre></div></div>';
if(k==="maintenance")return '<div class="mw-grid"><div class="mw-card"><h4>Maintenance Log</h4><div class="mw-row"><input id="mItem" placeholder="Mesin/peralatan"><input id="mHours" type="number" placeholder="Jam kerja"><button class="btn" id="mSave">Tambah</button></div><div id="mList" class="mw-list"></div></div><div class="mw-card"><h4>Engine Hours</h4><input id="engineHours" type="number" placeholder="Jam mesin"><button class="btn" id="engineSave">Simpan</button></div></div>';
if(k==="documents")return '<div class="mw-grid"><div class="mw-card"><h4>Document Vault</h4><div class="mw-row"><input id="dName" placeholder="Dokumen"><input id="dExp" type="date"><button class="btn" id="dSave">Simpan</button></div><div id="dList" class="mw-list"></div></div><div class="mw-card"><h4>File lokal</h4><input id="mwFile" type="file" accept="image/*,application/pdf" capture="environment"><p class="mw-muted">Metadata disimpan lokal.</p></div></div>';
if(k==="economy")return '<div class="mw-grid"><div class="mw-card"><h4>Trip P/L</h4><div class="mw-row"><input id="eFuel" type="number" placeholder="BBM Rp"><input id="eSupply" type="number" placeholder="Perbekalan Rp"><input id="eOther" type="number" placeholder="Lainnya Rp"></div><div class="mw-row"><input id="eCatch" type="number" placeholder="Nilai tangkapan Rp"><button class="btn primary-inline" id="eCalc">Hitung</button></div><div id="eOut" class="mw-value">—</div></div><div class="mw-card"><h4>Catat biaya</h4><div class="mw-row"><input id="eDesc" placeholder="Deskripsi"><input id="eAmount" type="number" placeholder="Rp"><button class="btn" id="eSave">Simpan</button></div><div id="eList" class="mw-list"></div></div></div>';
if(k==="social")return '<div class="mw-grid"><div class="mw-card"><h4>Marine Feed</h4><div class="mw-row"><textarea id="postText" placeholder="Bagikan kondisi laut/operasi"></textarea><button class="btn" id="postSave">Posting</button></div><div id="postList" class="mw-list"></div></div><div class="mw-card"><h4>Marine Data</h4><p class="mw-muted">Post disimpan lokal dan disinkronkan saat Supabase tersedia.</p></div></div>';
if(k==="messenger")return '<div class="mw-card"><h4>Offline-first Messenger</h4><div class="mw-row"><input id="msgTo" placeholder="Tujuan/user ID"><input id="msgText" placeholder="Pesan"><button class="btn" id="msgSave">Antrekan</button></div><div id="msgList" class="mw-list"></div><p class="mw-muted">Realtime memakai Supabase jika tersedia; offline tetap queued.</p></div>';
if(k==="data")return '<div class="mw-grid"><div class="mw-card"><h4>Observation Queue</h4><div class="mw-row"><input id="obsType" placeholder="Jenis"><input id="obsNote" placeholder="Catatan"><button class="btn" id="obsSave">Simpan</button></div><div id="obsList" class="mw-list"></div></div><div class="mw-card"><h4>Export</h4><button class="btn" id="exportAll">Ekspor semua Marine OS</button></div></div>';
if(k==="academy")return '<div class="mw-grid">'+["Keselamatan dasar","GNSS & posisi","Cuaca maritim","Navigasi dasar","AIS & COLREG","BBM & ekonomi","Logbook & maintenance"].map((x,i)=>'<div class="mw-card"><h4>'+x+'</h4><p class="mw-muted">Materi offline Marine OS.</p><button class="btn" data-lesson="'+i+'">'+(state.academyProgress[i]?"✓ Selesai":"Pelajari")+"</button></div>").join("")+"</div>";
if(k==="camera")return '<div class="mw-card"><h4>Marine Camera</h4><p class="mw-muted">Foto dengan timestamp dan GPS yang tersedia.</p><input id="marineCamera" type="file" accept="image/*" capture="environment"><div id="cameraOut"></div></div>';
if(k==="checklist")return '<div class="mw-card"><h4>Pre-departure Checklist</h4>'+["BBM cukup","Mesin diperiksa","GPS/GNSS aktif","Cuaca diperiksa","PFD tersedia","Komunikasi siap","Dokumen tersedia"].map((x,i)=>'<label class="switch-row"><span>'+x+'</span><input type="checkbox" data-check="'+i+'"></label>').join("")+'<button class="btn primary-inline" id="checkSave">Simpan checklist</button><div id="checkList" class="mw-list"></div></div>';
if(k==="digital-twin")return '<div class="mw-grid"><div class="mw-card"><h4>Digital Twin</h4><div id="twin"></div></div><div class="mw-card"><h4>Update</h4><div class="mw-row"><input id="tFuel" type="number" placeholder="Fuel %"><input id="tHours" type="number" placeholder="Engine hours"><select id="tStatus"><option>READY</option><option>UNDERWAY</option><option>MAINTENANCE</option><option>ALERT</option></select><button class="btn" id="tSave">Update</button></div></div></div>';
if(k==="ais")return '<div class="mw-grid"><div class="mw-card"><h4>AIS</h4><div class="mw-status">🟡 Provider/receiver belum terhubung</div><p class="mw-muted">Tidak ada target kapal palsu. AIS realtime memerlukan feed/provider atau receiver AIS.</p></div><div class="mw-card"><h4>CPA/TCPA</h4><p class="mw-muted">Engine siap menerima target; tanpa target tidak ada hasil yang dikarang.</p></div></div>';
if(k==="radar")return '<div class="mw-grid"><div class="mw-card"><h4>Radar simulator</h4><div class="mw-radar"></div><p class="mw-muted">Visual simulator saja, bukan radar navigasi.</p></div><div class="mw-card"><h4>Hardware gateway</h4><div class="mw-status">🟡 Belum terhubung</div></div></div>';
return '<div class="mw-card"><h4>Marine Copilot lokal</h4><div class="mw-row"><textarea id="aiPrompt" placeholder="Tanya rute, safety, checklist, biaya…"></textarea><button class="btn primary-inline" id="aiRun">Analisis</button></div><div id="aiOut" class="mw-status">Rule-based offline; cloud AI opsional.</div></div>';
}
function bind(c,k){
const m=window.MapApp;
if(k==="navigation"){c.querySelector("#mwTrackCount").textContent=m?.track?.getLatLngs?.().length||0;c.querySelector("#mwRoute").onclick=()=>{const lat=+c.querySelector("#mwLat").value,lon=+c.querySelector("#mwLon").value,sog=+c.querySelector("#mwSog").value||+(m?.speedKmh||0)/1.852;if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(m?.lat))return c.querySelector("#mwRouteOut").textContent="GPS/tujuan belum valid.";const d=MarineFree.distanceNm({lat:m.lat,lon:m.lon},{lat,lon}),b=MarineFree.bearing({lat:m.lat,lon:m.lon},{lat,lon}),eta=MarineFree.etaHours(d,sog);c.querySelector("#mwRouteOut").innerHTML="Jarak <b>"+fmt(d)+" NM</b> • Bearing <b>"+Math.round(b)+"°</b> • ETA "+(eta==null?"—":fmt(eta)+" jam")};c.querySelector("#mwExportTrack").onclick=()=>download("marine-track.json",localStorage.getItem("bs10_track")||"[]","application/json")}
if(k==="weather"){c.querySelector("#mwWeatherRefresh").onclick=()=>loadWeather(c);loadWeather(c)}
if(k==="fishing"){c.querySelector("#fishCalc").onclick=()=>{if(!Number.isFinite(m?.lat))return c.querySelector("#fishScore").textContent="GPS belum aktif";let s=50;if(m.speedKmh>1)s+=5;const h=new Date().getHours();if(h<8||h>17)s+=10;c.querySelector("#fishScore").textContent=Math.min(100,s)+"/100"};c.querySelector("#fishSave").onclick=()=>{add("catches",{species:c.querySelector("#fishSpecies").value,kg:+c.querySelector("#fishKg").value||0,lat:m?.lat,lon:m?.lon});render(c,"fishList",state.catches,x=>esc(x.species)+" • "+x.kg+" kg")};render(c,"fishList",state.catches,x=>esc(x.species)+" • "+x.kg+" kg")}
if(k==="safety"){const check=()=>{const issues=[];if(!Number.isFinite(m?.lat))issues.push("GNSS belum fix");if(!navigator.onLine)issues.push("Offline");const a=JSON.parse(localStorage.getItem("bs10_anchor")||"null");if(a&&Number.isFinite(m?.lat)){const d=MarineFree.distanceNm({lat:a.lat,lon:a.lon},{lat:m.lat,lon:m.lon})*1852;if(d>a.radius)issues.push("Anchor keluar radius "+Math.round(a.radius)+" m")}c.querySelector("#safeStatus").innerHTML=issues.length?issues.map(x=>"⚠️ "+esc(x)).join("<br>"):"🟢 Tidak ada kondisi lokal kritis terdeteksi."};check();c.querySelector("#mwSos").onclick=()=>add("observations",{type:"EMERGENCY_CHECKLIST",note:"Emergency checklist dimulai",lat:m?.lat,lon:m?.lon});c.querySelector("#anchorSet").onclick=()=>{if(!Number.isFinite(m?.lat))return;c.querySelector("#anchorStatus").textContent="Anchor "+m.lat.toFixed(5)+", "+m.lon.toFixed(5);localStorage.setItem("bs10_anchor",JSON.stringify({lat:m.lat,lon:m.lon,radius:+c.querySelector("#anchorRadius").value||100,at:new Date().toISOString()}))}}
if(k==="vessel"){const v=state.vessel;c.querySelector("#vName").value=v.name||"";c.querySelector("#vCaptain").value=v.captain||"";c.querySelector("#vGross").value=v.gross||"";c.querySelector("#vCargo").value=v.cargo||"";c.querySelector("#vJson").textContent=JSON.stringify(v,null,2);c.querySelector("#vSave").onclick=()=>{state.vessel={name:c.querySelector("#vName").value,captain:c.querySelector("#vCaptain").value,gross:+c.querySelector("#vGross").value||null,cargo:c.querySelector("#vCargo").value,updatedAt:new Date().toISOString()};save();sync("vessel",state.vessel);c.querySelector("#vJson").textContent=JSON.stringify(state.vessel,null,2)}}
if(k==="maintenance"){render(c,"mList",state.maintenance,x=>esc(x.item)+" • "+x.hours+" jam");c.querySelector("#mSave").onclick=()=>{add("maintenance",{item:c.querySelector("#mItem").value,hours:+c.querySelector("#mHours").value||0});WB.render()};c.querySelector("#engineHours").value=state.digitalTwin.engineHours;c.querySelector("#engineSave").onclick=()=>{state.digitalTwin.engineHours=+c.querySelector("#engineHours").value||0;save();WB.render()}}
if(k==="documents"){render(c,"dList",state.documents,x=>esc(x.name)+" • "+esc(x.exp||"—"));c.querySelector("#dSave").onclick=()=>{add("documents",{name:c.querySelector("#dName").value,exp:c.querySelector("#dExp").value});WB.render()}}
if(k==="economy"){render(c,"eList",state.expenses,x=>esc(x.desc)+" • Rp "+Number(x.amount).toLocaleString("id-ID"));c.querySelector("#eCalc").onclick=()=>{const cost=(+c.querySelector("#eFuel").value||0)+(+c.querySelector("#eSupply").value||0)+(+c.querySelector("#eOther").value||0),income=+c.querySelector("#eCatch").value||0;c.querySelector("#eOut").textContent="P/L Rp "+(income-cost).toLocaleString("id-ID")};c.querySelector("#eSave").onclick=()=>{add("expenses",{desc:c.querySelector("#eDesc").value,amount:+c.querySelector("#eAmount").value||0});WB.render()}}
if(k==="social"){render(c,"postList",state.observations.filter(x=>x.type==="POST"),x=>"<b>"+esc(x.note)+"</b>");c.querySelector("#postSave").onclick=()=>{add("observations",{type:"POST",note:c.querySelector("#postText").value,lat:m?.lat,lon:m?.lon});WB.render()}}
if(k==="messenger"){render(c,"msgList",state.messages,x=>"→ "+esc(x.to)+" • "+esc(x.text));c.querySelector("#msgSave").onclick=()=>{add("messages",{to:c.querySelector("#msgTo").value,text:c.querySelector("#msgText").value,status:navigator.onLine?"pending-sync":"queued"});WB.render()}}
if(k==="data"){render(c,"obsList",state.observations,x=>esc(x.type)+" • "+esc(x.note||""));c.querySelector("#obsSave").onclick=()=>{add("observations",{type:c.querySelector("#obsType").value,note:c.querySelector("#obsNote").value,lat:m?.lat,lon:m?.lon});WB.render()};c.querySelector("#exportAll").onclick=()=>download("marine-os-export.json",JSON.stringify({runtime:state,free:window.MarineFree?.state||null},null,2),"application/json")}
if(k==="academy")c.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>{state.academyProgress[b.dataset.lesson]=true;save();b.textContent="✓ Selesai"});
if(k==="camera")c.querySelector("#marineCamera").onchange=e=>{const f=e.target.files?.[0];if(f){add("observations",{type:"CAMERA",note:f.name,lat:m?.lat,lon:m?.lon});c.querySelector("#cameraOut").textContent="Foto tercatat: "+f.name}}
if(k==="checklist")c.querySelector("#checkSave").onclick=()=>{const items=[...c.querySelectorAll("[data-check]")].map(x=>x.checked);add("checklists",{kind:"pre-departure",items});c.querySelector("#checkList").textContent="Tersimpan "+new Date().toLocaleString("id-ID")};
if(k==="digital-twin"){c.querySelector("#twin").innerHTML="<b>Status:</b> "+esc(state.digitalTwin.status)+"<br><b>Fuel:</b> "+state.digitalTwin.fuelPct+"%<br><b>Engine:</b> "+state.digitalTwin.engineHours+" jam";c.querySelector("#tSave").onclick=()=>{state.digitalTwin={...state.digitalTwin,fuelPct:+c.querySelector("#tFuel").value||state.digitalTwin.fuelPct,engineHours:+c.querySelector("#tHours").value||state.digitalTwin.engineHours,status:c.querySelector("#tStatus").value};save();WB.render()}}
if(k==="ai")c.querySelector("#aiRun").onclick=()=>{const p=c.querySelector("#aiPrompt").value.toLowerCase();c.querySelector("#aiOut").textContent=p.includes("safety")?"Cek GNSS, cuaca BMKG, hazard, PFD, komunikasi dan rute; aplikasi hanya decision-support.":p.includes("rute")?"Gunakan Navigasi untuk jarak NM, bearing dan ETA.":p.includes("biaya")?"Gunakan Ekonomi untuk P/L perjalanan.":"Mode lokal belum punya knowledge khusus untuk pertanyaan itu; cloud AI dapat dipasang sebagai adapter opsional."}
}
async function loadWeather(c){const m=window.MapApp;if(!Number.isFinite(m?.lat))return c.querySelector("#mwWeather").textContent="GPS belum aktif.";c.querySelector("#mwWeather").textContent="Mengambil BMKG…";try{const result=window.MarineExternal?.bmkg?.weather?await MarineExternal.bmkg.weather(m.lat,m.lon):null;const code=result?.code;if(!code)throw new Error("Kode wilayah BMKG tidak ditemukan");const raw=result.raw||await bmkg("perairan/"+code+".json");const first=raw?.forecast_day1?.[0]||raw?.data?.[0]||raw?.forecast?.[0]||raw;c.querySelector("#mwWeather").innerHTML="<b>Wilayah "+esc(result.region||code)+"</b><br><small>Jarak area: "+fmt(result.distanceKm)+" km</small><br><pre class='mw-muted'>"+esc(JSON.stringify(first,null,2).slice(0,1800))+"</pre>"}catch(e){c.querySelector("#mwWeather").textContent="BMKG gagal dimuat: "+e.message}}
function render(c,id,arr,fn){list(c,id,arr,fn)}
window.MarineRuntime={state,open:k=>WB.open(k),close:()=>WB.close(),add,save};
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".marine-module[data-marine-target]").forEach(b=>b.addEventListener("click",e=>{const t=e.currentTarget.dataset.marineTarget;if(["peta","cuaca","akun","pengaturan","story","tangkapan","kolekting","perbekalan","kru","riwayat"].includes(t))return;e.preventDefault();WB.open(t)}))});
})();